
export V?=0

.PHONY: all
all:
#	$(MAKE) -C fTPM CROSS_COMPILE=$(TA_CROSS_COMPILE)
	$(MAKE) -C AuthVars CROSS_COMPILE=$(TA_CROSS_COMPILE)

.PHONY: clean
clean:
#	$(MAKE) -C fTPM clean
	$(MAKE) -C AuthVars clean